# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '03.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 160)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 10, 240, 120))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "启动：alt+f"))
        self.label_2.setText(_translate("MainWindow", "暂停：长按v"))
        self.pushButton.setText(_translate("MainWindow", "启动(alt+f)"))

if __name__ == '__main__':
    # 创建进程
    app = QtWidgets.QApplication(sys.argv)
    # 创建窗口
    MainWindow = QtWidgets.QMainWindow()
    # 实例化类 （类的初始化）
    ui = Ui_MainWindow()
    # setupUi()这个函数的作用是对界面进行初始化，它按照我们在QtDesigner里设计的样子把窗体画出来
    # 画在哪里？ 画在下面的参数 MainWindow 上
    ui.setupUi(MainWindow)
    # 显示窗口
    MainWindow.show()
    # app.exec_() 点击关闭按钮，返回 0
    # sys.exit() 对事件进行无限循环监听
    # sys.exit(0)，Break退出循环，sys.exit(1)一直执行，死循环，无限循环
    sys.exit(app.exec_())
